<a href="https://colab.research.google.com/github/sakuronohana/my_datascience/blob/master/udemy/mlaz/Part%208%20-%20Deep%20Learning/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning

### Was ist Deep Learning?###

Deep Learning ist ein Teilgebiet des Machine Learning und unterscheidet sich vom „klassischen“ maschinellen Lernen, indem es Maschinen in die Lage versetzt, über die verfügbaren Daten hinaus zu lernen. Das beinhaltet die Fähigkeit, Informationen zu analysieren und zu bewerten, um logische Schlüsse zu ziehen, Lösungswege auszuwählen und aus Fehlern zu lernen. Je mehr Daten eine Maschine also empfängt, desto grösser ist ihre Lernfähigkeit und desto "intelligenter" kann sie werden. Obwohl es die künstlichen neuronalen Netze, die die Grundlage dieser Technologien bilden, bereits seit den 1950er Jahren gibt, haben erst die bahnbrechenden Entwicklungen des letzten Jahrzehnts die Lernkurve stark verbessert. Die am meisten verbreiteten modernen Applikationen sind Stimm- und Bilderkennung. Das Niveau der Datenanalyse ermöglicht jedoch viele vorausschauende Applikationen, wie enorme Verbesserungen in der vorausschauenden Wartung, sicherere autonome Fahrzeuge, die Vorhersage von Krankheiten oder Rückfällen.

Einer der Pioniere in diesem Gebiet ist (Geoffrey Hinton)[https://de.wikipedia.org/wiki/Geoffrey_Hinton]. Hinton ist ein britischer Informatiker und Kognitionspsychologe der als Professor an der Universität Toronto und bei Google arbeitet. Er hat massgeblich den Begriff Deep Learning kreiert.



### Was sind Neuronale Netzwerke?

Ein künstliches neuronales Netzwerk (KNN), im englischen Artificial neural networks (ANN) genannt,  ist einen Art Abbildung des menschlichen neuronalen Netzwerks. Diese Netzwerk besteht aus vernetzten Neuronen. In einem KNN ist ein Neuron nichts anderes als eine Element welche eine Nummer zwischen 0 - 1, speichert. In einem KNN gibt es drei Arten von Neuronen - Input Neuron, Hidden Neuron und Output Neuron.

Beispiel ein Bild mit einer handschriftlichen Zahl 9 besteht aus 28 x 28 Pixel was somit 784 Neuronen darstellt. Jeder dieser Neuronen enthält einen Graustufenwert von 0.01 (Schwarz) zu 1.00 (Weiss). Diese Werte werden „Activation“ genannt. Dies 784 Neuronen stellen die erste Schicht unsere Netzwerks dar. Die letze Schicht wird nur noch aus 10 Neuronen welche die Nummern 0 - 9 darstellen. Die Schichten dazwischen werden „Hidden Layers“ genannt. Sämtliche Neuronen in den verschiedenen Layers sind miteinander verbunden. Die Verbindungen zwischen den Neuronen haben eigene Gewichtungen. Diese Gewichtung wird mit dem Input-Wert multipliziert. Hat also beispielsweise ein Input-Neuron einen Wert von 0,7 und die Gewichtung der Verbindung einen Wert von 2 werden diese zwei Werte multipliziert und ergeben einen Wert von 1.4, welcher an das nächste Neuron weitergegeben werden. Würden wir aber nun immer so rechnen, würde das Resultat immer durch null gehen. Damit wir das verhindern können benutzen wir den Bias. Der Bias ist nichts anderes als der y-Intercept in der linearen Algebra mit dem Unterschied, dass er nur 1 sein kann. Nehmen wir nun also den Bias noch dazu dann bekommen wir folgenden Formel f(x) = mx + b.

In einem künstlich neuronalen Netzwerk bestimmen die Aktivitäten in einem Layer die Aktivitäten im nächsten Layer. Die grosse Frage ist dabei WIE Aktivitäten in einem Layer die des nächsten beeinflusst. Grundsätzlich funktioniert es in der gleichen Art wie das biologische Vorbild. Feuert ein Neuron beeinflusst es ein anderes Neuron.

Hier eine Abbildung eines typischen KNN:

![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/MultiLayerNeuralNetworkBigger_english.png/880px-MultiLayerNeuralNetworkBigger_english.png)

###Anatomie eines KNN###

Nachfolgenden werden wir die verschiedenen Bestandteile (inkl. Math) eines KNN erläutern

**Künstliches Neuron (Unit)**

Ein künstliches Neuron stellt ein vereinfachtes Modell eines biologischen Neurons dar.  Ein künstliches Neuron wird auch oft McCulloch-Pittsburgh-Zelle genannt. Bei der Definition des künstlichen Neurons wurden die wesentlichen Eigenschaften eines biologischen Neurons dargestellt:

* Synapsen der Nervenzellen = Addition gewichteter EIngaben
* Aktivierung Zellkerns = Aktivierungsfunktion mit Schwellwerten



**Perzeptron**

Ausgehen von dieser Idee hat Frank Rosenblatt 1957 das Perzepton entwickelt. Dieses Perzeptron stellt das einfachste KNN dar, da es aus einer Eingabeschicht und einer Ausgabeschicht besteht:

![alt text](https://www.statworx.com/wp-content/uploads/perceptron.png)

Das Perzeptron besteht aus folgenden Teilen:

1. **Input-Layer**. Der Input-Layer beinhaltet einerseits die Daten (x) und eine Bias-Unit (1)
2. **Wichtung (w)**. Die Gewichtung wird pro Verbindung zwischen dem Input und Output dargestellt und beinhaltet irgend einen Wert. 
2. **Output-Layer** Die Ausgabeschicht besteht im wesentlichen aus der **Linear Threshold Unit (LTU)** welche folgende Funktionen beinhaltet: 
 * **Übertragungsfunktion**. Diese Funktion (∑) berechnet die Wichtung mal Input plus Bias:
 
 $\displaystyle \sum_{i=1}^{n} =  (w_1 * _1 + w_2 * x_2 + w_n * x_n) + Bias$

3. **Aktivierungsfunktion (ρ)**. Diese Funktion bestimmt die Ausgabe des Neurons. Sie wird durch die Netzeingabe und den Schwellwert beeinflusst. -> Siehe Activation Functions
4. **Schwellwert (θj)**. Das Addieren eines Schwellwerts zur Netzeingabe verschiebt die gewichtete Eingabe.



**Input Layer**

Die Daten werden über den Input Layer in das KNN übergeben. Im ersten Layer finden somit noch keine eigentlichen mathematischen Operationen statt und es gibt dort auch keine eigentlichen Knoten wie es in manchen Darstellungen suggeriert wird. Die Daten werden mittels eines 1D-Arrays in die Input-Schicht 

###Automated Machine Learning###

**Tutorial:** [lntroduction: Automated Machine Learning](https://colab.research.google.com/drive/1CIVn-GoOyY3H2_Bv8z09mkNRokQ9jlJ-#scrollTo=rbiKVIwfHxxS)

**Weitere Infos:** [Home TPOT](https://epistasislab.github.io/tpot/)

In [ ]:
# Install Upgrade Scikit-Learn 0.20 for AutoSklearn on the server
!pip install --upgrade scikit-learn




In [ ]:
# Install tpot on the server
!pip install tpot

# Install AutoSklearn on the server
!pip install auto-sklearn

In [ ]:
# pandas and numpy for data manipulation
import pandas as pd
import numpy as np

# Import the tpot regressor
from tpot import TPOTRegressor

import autosklearn.classification

##Modellentwicklung##




###ML Frameworks###

Im Internet existieren bereits veschiedenen Frameworks zur Entwicklung von Machine Learning Modellen. Nachfolgenden werden ein paar der wichtigsten kurz vorgestellt:

### Apache MXnet ###

<img src='https://raw.githubusercontent.com/dmlc/web-data/master/mxnet/image/mxnet_logo_2.png' width='300'>

MXNet ist ein Open Source Framework der Apache Software Foundation, das sich für maschinenbasiertes Lernen und Deep Learning einsetzen lässt. Es gestattet das Trainieren von neuronalen Netzen und unterstützt unterschiedliche Plattformen und Programmiersprachen (C++, JavaScript, Python, R, Julia, Scala etc.). Das Deep Learning Framework Apache MXnet wird in vielen Universitäten zur Vermittlung des Deep Learning Themas verwendet. 

Die Gluon-Schnittstelle lässt sich zusammen mit MXNet verwenden. Bei Gluon handelt es sich um ein Deep Learning Interface von Microsoft und Amazon, das Programmierern über standardisierte APIs (Application Programming Interfaces) einen einfachen Zugang zu MXNet mit seinem Deep Learning Framework und den neuronalen Netzen bietet.

Quelle: [Apache MXNet (Github) for Deep Learning](https://github.com/apache/incubator-mxnet/blob/master/README.md)


In [ ]:
# Installation Framework - Hinweis: Auf Colab ist das Packet bereits installiert.

!pip install mxnet

In [ ]:
# Mxnet NDArray laden
from mxnet import nd

In [ ]:
# Erstellen eines NDArrays

x = nd.array([3.0])
y = nd.array([2.0])

print('x + y = ', x + y)
print('x * y = ', x * y)
print ('x / y = ', x /y)
print('x ** y = ', nd.power(x,y))



[3.]
<NDArray 1 @cpu(0)>
3.0
x + y =  
[5.]
<NDArray 1 @cpu(0)>
x * y =  
[6.]
<NDArray 1 @cpu(0)>
x / y =  
[1.5]
<NDArray 1 @cpu(0)>
x ** y =  
[9.]
<NDArray 1 @cpu(0)>


In [ ]:
x = nd.arange(5)
print('x = ', x)
print ('Zugriff auf das dritte Element ', x[3])

print(x.shape)
print(len(x))


x =  
[0. 1. 2. 3. 4.]
<NDArray 5 @cpu(0)>
Zugriff auf das dritte Element  
[3.]
<NDArray 1 @cpu(0)>
(5,)
5


In [ ]:
# Unterschied 2D und 3D

a = 2
x = nd.array([1,2,3])
y = nd.array([10,20,30])
print(a * x)
print(a * x * y)


[2. 4. 6.]
<NDArray 3 @cpu(0)>

[ 20.  80. 180.]
<NDArray 3 @cpu(0)>


In [ ]:
# Matrixen

a = nd.arange(20)
print(a)
print(a.reshape((5,2)))


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
<NDArray 20 @cpu(0)>

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
<NDArray 5x2 @cpu(0)>


In [ ]:
#Transponieren

a = a.reshape((5,2))
print(a)

b = a.T
b


[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
<NDArray 5x2 @cpu(0)>



[[0. 2. 4. 6. 8.]
 [1. 3. 5. 7. 9.]]
<NDArray 2x5 @cpu(0)>

##Modelltraining (Train Model)


##Modelltesting (Test Model)##


##Modelloptimierung (Tune Model)##


##Modellproduktivsetzung (Prediction)##