<a href="https://colab.research.google.com/github/sakuronohana/my_datascience/blob/master/udemy/mlaz/Part%202%20-%20Regression/Section%205%20-%20Multiple%20Linear%20Regression/Python/multiple_linear_regression_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

Da Datensätze meist über mehrere Features verfügen macht eine Multiple Linear Regression am meisten Sinn. Grundsätzlich unterscheidet sich die Formel zur Simple Linear Regression nur dadurch, dass sie über mehrere Koeffizienten und unabhängige Variablen verfügt.

$y = b_0 + b_1x_1+b_2x_2+ ... + b_nx_n$

Wichtig dabei ist. Jede unhängige Variable ($x_1...x_n$) stellt ein Feature (Spalte) dar. Bspw. Ausgaben Administration, Ausgaben Marketing usw. 

## Importing the libraries

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing the dataset

In [48]:
daturl = 'https://raw.githubusercontent.com/sakuronohana/my_datascience/master/udemy/mlaz/Part%202%20-%20Regression/Section%205%20-%20Multiple%20Linear%20Regression/Python/50_Startups.csv'
dataset = pd.read_csv(daturl)

X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values


In [ ]:
print(X)

## Encoding categorical data

In [52]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [53]:
print (X)
print ('Wie wir oben sehen können, wurden die kodierten kategorischen Werte an den Anfang des Datensatzes gestellt')

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

## Features Scaling

An dieser Stelle stellt sich nun die Frage, ob wir die nummerischen Features skalieren müssen oder nicht.

Die Antwort ist ... **Nein** müssen wir nicht. 

Der Grund dafür ist, dass in der multiplen Linearen Regression alle unabhängigen Variablen ($x_1 ... x_n$) mit dem gleichen Koeffizienten ($b_1 ... b_n$) multipliziert werden und dieser, ungeachtet der Grösse des Wertes der unabhängigen Variablen, die Unterschiede kompensiert und jeden Wert gleich skaliert.

## Splitting the dataset into the Training set and Test set

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 0)

In [55]:
y_train.shape

(40,)

## Training the Multiple Linear Regression model on the Training set

An dieser Stelle gibt es noch etwas ganz wichtige zu sagen. 
Bei der Konzeption von Modellen wird oft erwähnt, dass beim Feature Engineering zuerst die Features mit der grössten statischen Signifikats ($p$) selektioniert werden müssen, bevor ein Modell erstellt werden kann.

Das stimmt so nicht immmer, da die meisten ML Tools wie Scikit automatisch die signifikatesten Features auswählen.

In [56]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the Test set results

In [66]:
y_pred = regressor.predict(X_test)

# Da wir relative viele Stellen nach dem Komma haben, wollen wir diese nachfolgend auf zwei Stellen einschränken.
np.set_printoptions(precision=2)

'''Mit den folgenden Codezeilen werden die Resultate aus dem y_pred und die Values aus den y_test
verkettet (Concanated) und horizontal für den Vergleich dargestellt '''

print('Links ist jeweils das Resultat der Prediction und rechts die Werte der Y-Testdaten. Die meisten Resultate sind verhältnismässig Nahe bei einander, was eine gute Accuracy des Modells aufzeigt')
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

Links ist jeweils das Resultat der Prediction und rechts die Werte der Y-Testdaten. Die meisten Resultate sind verhältnismässig Nahe bei einander, was eine gute Accuracy des Modells aufzeigt
[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]


## Visualising the Training set result

Wir können uns an dieser Stelle noch daran erinnern, wie wir die Trainingsresultate der einfachen linearen Regression visualisiert haben. Leider funktioniert diese Methode hier nicht, da wir mehrer Features haben und diesbezüglich einen fünf dimensionalen Graphen erstellen müssten (schon 3D ist eine Herausforderung ;-)).