<a href="https://colab.research.google.com/github/sakuronohana/my_datascience/blob/master/udemy/mlaz/Part%203%20-%20Classification/Section%2010%20-%20Model%20Selection%20Classification/classifier_model_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classification Model Selection

In diesem Notebook werden wir eine klassische Modell Selektion vornehmen. Dazu werden wir verschiedene Klassifikatoren auf einen Datensatz trainineren und mittels Performance-Messungen das beste Modell auswählen.

## Importing the libraries

In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [22]:
datloc = ('https://raw.githubusercontent.com/sakuronohana/my_datascience/master/udemy/mlaz/Part%203%20-%20Classification/Section%2010%20-%20Model%20Selection%20Classification/Data.csv')

dataset = pd.read_csv(datloc)
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

## Splitting the dataset into the Training set and Test set

In [23]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25, random_state=0)

## Feature Scaling

In [24]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Train and Test different Classification models

### 1. Model - Linear Logistic Regression Classificator

In [25]:
# Train
from sklearn.linear_model import LogisticRegression
clf_logreg = LogisticRegression(random_state=0)
clf_logreg.fit(X_train,y_train)

# Test 
y_pred_logreg = clf_logreg.predict(X_test)

### 2. Model - KNeighbors Model

In [27]:
# Train
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier(n_neighbors=10, p=2)
clf_knn.fit(X_train, y_train)

# Test
y_pred_knn = clf_knn.predict(X_test)

### 3. Model - Linear Support Vector Classification (SVC)

In [29]:
# Train
from sklearn.svm import SVC
clf_linsvc = SVC(random_state=0, kernel='linear')
clf_linsvc.fit(X_train,y_train)

# Test
y_pred_linsvc = clf_linsvc.predict(X_test)

### 4. Model - RBF Support Vector Classificator

In [30]:
# Train
from sklearn.svm import SVC
clf_rbfsvc = SVC(random_state=0, kernel='rbf')
clf_rbfsvc.fit(X_train,y_train)

# Test
y_pred_rbfsvc = clf_rbfsvc.predict(X_test)

### 5. Model -Naive Bayes Classificator

In [31]:
# Train
from sklearn.naive_bayes import GaussianNB
clf_gausnb = GaussianNB()
clf_gausnb.fit(X_train, y_train)

# Test
y_pred_gausnb = clf_gausnb.predict(X_test)

### 6. Model - Decision Tree Classificator

In [32]:
# Train
from sklearn.tree import DecisionTreeClassifier
clf_dtree = DecisionTreeClassifier(random_state=0, criterion='entropy')
clf_dtree.fit(X_train,y_train)

# Test
y_pred_dtree = clf_dtree.predict(X_test)

### 7. Model - Random Forest Classificator

In [33]:
# Train
from sklearn.ensemble import RandomForestClassifier
clf_ranfor = RandomForestClassifier(n_estimators=10,random_state=0, criterion='entropy')
clf_ranfor.fit(X_train,y_train)

# Test
y_pred_ranfor = clf_ranfor.predict(X_test)

## Measure classification performance.

### Measure Accuracy Score

In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score

print('List of Accuracy Scores:')
print('Linear Logistic Regression:',round(accuracy_score(y_test,y_pred_logreg),3))
print('KNeighbors:',round(accuracy_score(y_test,y_pred_knn),3))
print('Linear Support Vector (SVC):',round(accuracy_score(y_test,y_pred_linsvc),3))
print('SVM RBF-Kernel:',round(accuracy_score(y_test,y_pred_rbfsvc),3))
print('Naive Bayes:',round(accuracy_score(y_test,y_pred_gausnb),3))
print('Decision Tree:',round(accuracy_score(y_test,y_pred_dtree),3))
print('Random Forest:',round(accuracy_score(y_test,y_pred_ranfor),3))

List of Accuracy Scores
Linear Logistic Regression: 0.947
KNeighbors: 0.942
Linear Support Vector (SVC): 0.942
SVM RBF-Kernel: 0.953
Naive Bayes: 0.942
Decision Tree: 0.959
Random Forest: 0.936


In [53]:
print('Confusion matrix of top 3 Models:')
print('Decision Tree: \n', confusion_matrix(y_test,y_pred_dtree))
print('SVM RBF-Kernel: \n', confusion_matrix(y_test,y_pred_rbfsvc))
print('Linear Logistic Regression: \n', confusion_matrix(y_test,y_pred_linsvc))

Confusion matrix of top 3 Models:
Decision Tree: 
 [[103   4]
 [  3  61]]
SVM RBF-Kernel: 
 [[102   5]
 [  3  61]]
Linear Logistic Regression: 
 [[102   5]
 [  5  59]]
